### ISSUE TITLE
Sharing puzzle inputs

### ISSUE THREAD

**Issue by codemicro** [natecraddock/aoc#1]
Just thought I'd give a quick heads up that [it's requested that folks don't share puzzle inputs to challenges](https://old.reddit.com/r/adventofcode/comments/k99rod/sharing_input_data_were_we_requested_not_to/gf2ukkf/?context=3) :)

Best of luck with your AoC!

\- AKU

**Comment by natecraddock** [comment]
I had no idea! Thanks for pointing that out! I'll get that cleaned up right away
